[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 150
dimensions.lines = 60
     
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.95
blur = true

#option_as_alt = "Both"

[font]
#normal.family = "Hack Nerd Font Mono"
normal.family = "MesloLGS Nerd Font Mono"

size = 12
